import { SECURITY_AUDIT_EVENT_DESCRIPTIONS } from "./generated/securityAuditEvents";
import { NSA_RECOMMENDED_EVENT_DESCRIPTIONS } from "./generated/nsaRecommendedEvents";

const COMMON_EVENT_CODE_DESCRIPTIONS: Record<string, string> = {
  "0": "Event logging service started",
  "1": "Process created (Sysmon)",
  "2": "File creation time changed (Sysmon)",
  "3": "Network connection (Sysmon)",
  "4": "Sysmon service state changed",
  "5": "Process terminated (Sysmon)",
  "6": "Driver loaded (Sysmon)",
  "7": "Image loaded (Sysmon)",
  "8": "CreateRemoteThread (Sysmon)",
  "9": "Raw disk access read (Sysmon)",
  "10": "Process access (Sysmon)",
  "11": "File created (Sysmon)",
  "12": "Registry object create/delete (Sysmon)",
  "13": "Registry value set (Sysmon)",
  "14": "Registry object renamed (Sysmon)",
  "15": "File stream created (Sysmon)",
  "16": "Sysmon config changed",
  "17": "Named pipe created (Sysmon)",
  "18": "Named pipe connected (Sysmon)",
  "19": "WMI event filter created (Sysmon)",
  "20": "WMI event consumer created (Sysmon)",
  "21": "WMI filter-to-consumer binding (Sysmon)",
  "22": "DNS query (Sysmon)",
  "23": "File delete (Sysmon)",
  "24": "Clipboard changed (Sysmon)",
  "25": "Process tampering (Sysmon)",
  "26": "File delete detected (Sysmon)",
  "27": "File block executable (Sysmon)",
  "28": "File block shimming (Sysmon)",
  "29": "File executable detected (Sysmon)",
  "104": "Security log cleared",
  "106": "Scheduled task registered",
  "800": "PowerShell pipeline execution details",
  "1100": "Event logging service shutdown",
  "1102": "Audit log cleared",
  "1149": "Remote Desktop logon succeeded",
  "4103": "PowerShell module logging",
  "4104": "PowerShell script block logging",
  "4105": "PowerShell command started",
  "4106": "PowerShell command completed",
  "4608": "Windows startup complete",
  "4609": "Windows shutdown initiated",
  "4610": "Trusted logon process registered",
  "4611": "Trusted logon process removed",
  "4616": "System time changed",
  "4618": "Monitored security event pattern",
  "4621": "Admin recovered system from crash",
  "4624": "Logon succeeded",
  "4625": "Logon failed",
  "4626": "User/device claims info",
  "4627": "Group membership info",
  "4634": "Logoff",
  "4647": "User initiated logoff",
  "4648": "Logon with explicit credentials",
  "4649": "Replay attack detected",
  "4656": "Handle requested to object",
  "4657": "Registry value modified",
  "4658": "Handle closed to object",
  "4660": "Object deleted",
  "4661": "Handle requested to AD object",
  "4662": "Operation performed on object",
  "4663": "Object access attempt",
  "4664": "Hard link created",
  "4665": "Object delete attempt",
  "4666": "Application attempted object access",
  "4667": "Application client context generated",
  "4670": "Object permissions changed",
  "4671": "Application attempted privileged service access",
  "4672": "Special privileges assigned",
  "4673": "Privileged service called",
  "4674": "Privileged object operation attempted",
  "4675": "SID filtered",
  "4688": "Process created",
  "4689": "Process exited",
  "4690": "Handle duplicated",
  "4691": "Indirect object access requested",
  "4692": "DPAPI backup attempted",
  "4693": "DPAPI recovery attempted",
  "4694": "Data protection key backup attempted",
  "4695": "Data protection key recovery attempted",
  "4696": "Primary token assigned to process",
  "4697": "Service installed (security log)",
  "4698": "Scheduled task created",
  "4699": "Scheduled task deleted",
  "4700": "Scheduled task enabled",
  "4701": "Scheduled task disabled",
  "4702": "Scheduled task updated",
  "4703": "Token rights adjusted",
  "4704": "User right assigned",
  "4705": "User right removed",
  "4706": "Trust created for domain",
  "4707": "Trust removed for domain",
  "4709": "IPsec services started",
  "4710": "IPsec services disabled",
  "4713": "Kerberos policy changed",
  "4714": "Encrypted data recovery policy changed",
  "4715": "Audit policy (SACL) changed",
  "4716": "Trusted domain info modified",
  "4717": "System security access granted",
  "4718": "System security access removed",
  "4719": "Audit policy changed",
  "4720": "User account created",
  "4722": "User account enabled",
  "4723": "Password change attempt",
  "4724": "Password reset attempt",
  "4725": "User account disabled",
  "4726": "User account deleted",
  "4727": "Security-enabled global group created",
  "4728": "Member added to global security group",
  "4729": "Member removed from global security group",
  "4730": "Security-enabled global group deleted",
  "4731": "Security-enabled local group created",
  "4732": "User added to security group",
  "4733": "User removed from security group",
  "4734": "Security-enabled local group deleted",
  "4735": "Security-enabled local group changed",
  "4737": "Security-enabled global group changed",
  "4738": "User account changed",
  "4739": "Domain policy changed",
  "4740": "User account locked out",
  "4741": "Computer account created",
  "4742": "Computer account changed",
  "4743": "Computer account deleted",
  "4744": "Security-disabled local group created",
  "4745": "Security-disabled local group changed",
  "4746": "Member added to disabled local group",
  "4747": "Member removed from disabled local group",
  "4748": "Security-disabled local group deleted",
  "4749": "Security-disabled global group created",
  "4750": "Security-disabled global group changed",
  "4751": "Member added to disabled global group",
  "4752": "Member removed from disabled global group",
  "4753": "Security-disabled global group deleted",
  "4754": "Security-enabled universal group created",
  "4755": "Security-enabled universal group changed",
  "4756": "Member added to universal security group",
  "4757": "Member removed from universal security group",
  "4758": "Security-enabled universal group deleted",
  "4759": "Security-disabled universal group created",
  "4760": "Security-disabled universal group changed",
  "4761": "Member added to disabled universal group",
  "4762": "Member removed from disabled universal group",
  "4763": "Security-disabled universal group deleted",
  "4764": "Group type changed",
  "4765": "SID History added",
  "4766": "SID History add failed",
  "4767": "User account unlocked",
  "4768": "Kerberos TGT requested",
  "4769": "Kerberos service ticket requested",
  "4770": "Kerberos service ticket renewed",
  "4771": "Kerberos pre-auth failed",
  "4772": "Kerberos auth ticket request failed",
  "4773": "Kerberos service ticket request failed",
  "4774": "Account mapped for logon",
  "4775": "Account mapping failed",
  "4776": "NTLM authentication attempted",
  "4777": "Domain controller failed to validate creds",
  "4778": "RDP session reconnected",
  "4779": "RDP session disconnected",
  "4780": "ACL set on AD account",
  "4781": "Account name changed",
  "4793": "Password policy checked",
  "4794": "DSRM password set attempt",
  "4797": "Blank password account query attempt",
  "4798": "User local group memberships enumerated",
  "4799": "Security-enabled local group membership enumerated",
  "4800": "Workstation locked",
  "4801": "Workstation unlocked",
  "4802": "Screen saver invoked",
  "4803": "Screen saver dismissed",
  "4816": "RPC detected integrity violation",
  "4817": "Auditing settings for object changed",
  "4825": "DACL check bypass detected",
  "4826": "Boot configuration data loaded",
  "4870": "Certificate services revoked cert",
  "4886": "Certificate request received",
  "4887": "Certificate request approved",
  "4888": "Certificate request denied",
  "4898": "Certificate template loaded",
  "4902": "Per-user audit policy table created",
  "4904": "Security event source registered",
  "4905": "Security event source unregistered",
  "4907": "Object auditing settings changed",
  "4908": "Special groups logon table modified",
  "4912": "Per-user audit policy changed",
  "4931": "Code Integrity policy changed",
  "4946": "Windows Firewall rule added",
  "4947": "Windows Firewall rule modified",
  "4948": "Windows Firewall rule deleted",
  "4950": "Windows Firewall setting changed",
  "4954": "Windows Firewall group policy changed",
  "4964": "Special groups assigned to new logon",
  "4965": "SID history checked",
  "4976": "IPsec dropped packet",
  "4977": "IPsec accepted packet",
  "4985": "Transaction state changed",
  "5001": "Windows Firewall service changed",
  "5024": "Windows Firewall started",
  "5025": "Windows Firewall stopped",
  "5031": "App blocked from internet by firewall",
  "5038": "Code integrity determined file invalid",
  "5058": "Cryptographic key operation",
  "5059": "Cryptographic key migration",
  "5061": "Cryptographic operation",
  "5136": "Directory service object modified",
  "5137": "Directory service object created",
  "5138": "Directory service object undeleted",
  "5139": "Directory service object moved",
  "5140": "Network share accessed",
  "5142": "Network share added",
  "5143": "Network share modified",
  "5144": "Network share deleted",
  "5145": "Network share object checked",
  "5148": "Network share object deleted",
  "5152": "WFP blocked packet",
  "5154": "WFP allowed app listen port",
  "5156": "WFP allowed connection",
  "5157": "WFP blocked connection",
  "5158": "WFP allowed bind",
  "5159": "WFP blocked bind",
  "5168": "SPN check for account failed",
  "5378": "Requested credentials delegation",
  "5379": "Credential Manager credentials read",
  "5381": "Credential Manager credentials written",
  "5416": "External device recognized",
  "5460": "Packet dropped due to callout",
  "5471": "IPsec quick mode SA ended",
  "5472": "IPsec quick mode SA established",
  "5480": "IPsec main mode SA established",
  "5485": "IPsec main mode SA ended",
  "5632": "Process opened to query token",
  "5633": "Process attempted token duplication",
  "6005": "Event log service started",
  "6006": "Event log service stopped",
  "6008": "Unexpected shutdown",
  "6013": "System uptime milestone",
  "7030": "Service misconfigured (desktop interaction)",
  "7034": "Service terminated unexpectedly",
  "7036": "Service state changed",
  "7040": "Service start type changed",
  "7045": "Service installed",
};

// Keep this map provider-specific because many Windows event IDs overlap.
// Add new providers/codes here as we expand coverage.
const PROVIDER_EVENT_CODE_DESCRIPTIONS: Record<string, Record<string, string>> = {
  sysmon: {
    ...(NSA_RECOMMENDED_EVENT_DESCRIPTIONS.sysmon ?? {}),
    "1": "Process created",
    "2": "File creation time changed",
    "3": "Network connection",
    "4": "Service state changed",
    "5": "Process terminated",
    "6": "Driver loaded",
    "7": "Image loaded",
    "8": "CreateRemoteThread",
    "9": "Raw disk access read",
    "10": "Process access",
    "11": "File created",
    "12": "Registry object create/delete",
    "13": "Registry value set",
    "14": "Registry object renamed",
    "15": "File stream created",
    "16": "Config changed",
    "17": "Named pipe created",
    "18": "Named pipe connected",
    "19": "WMI event filter created",
    "20": "WMI event consumer created",
    "21": "WMI filter-to-consumer binding",
    "22": "DNS query",
    "23": "File delete",
    "24": "Clipboard changed",
    "25": "Process tampering",
    "26": "File delete detected",
    "27": "File block executable",
    "28": "File block shimming",
    "29": "File executable detected",
  },
  security: {
    ...SECURITY_AUDIT_EVENT_DESCRIPTIONS,
    ...(NSA_RECOMMENDED_EVENT_DESCRIPTIONS.security ?? {}),
  },
  powershell: {
    ...(NSA_RECOMMENDED_EVENT_DESCRIPTIONS.powershell ?? {}),
    "800": "Pipeline execution details",
    "4103": "Module logging",
    "4104": "Script block logging",
    "4105": "Command started",
    "4106": "Command completed",
  },
  system: {
    ...(NSA_RECOMMENDED_EVENT_DESCRIPTIONS.system ?? {}),
    "7034": "Service terminated unexpectedly",
    "7036": "Service state changed",
    "7040": "Service start type changed",
    "7045": "Service installed",
    "6005": "Event log service started",
    "6006": "Event log service stopped",
    "6008": "Unexpected shutdown",
  },
  taskscheduler: {
    ...(NSA_RECOMMENDED_EVENT_DESCRIPTIONS.taskscheduler ?? {}),
    "100": "Task started",
    "101": "Task start failed",
    "102": "Task completed",
    "103": "Task failed to start instance",
    "106": "Task registered",
    "107": "Task triggered on scheduler",
    "108": "Task triggered by event",
    "109": "Task disabled",
    "110": "Task triggered by user",
    "111": "Task terminated",
    "140": "Task registration updated",
    "141": "Task deleted",
    "142": "Task disabled at registration",
    "200": "Action started",
    "201": "Action completed",
    "202": "Action failed",
  },
  defender: {
    ...(NSA_RECOMMENDED_EVENT_DESCRIPTIONS.defender ?? {}),
    "1000": "Scan started",
    "1001": "Scan completed",
    "1002": "Scan stopped",
    "1006": "Malware detected",
    "1007": "Malware action taken",
    "1008": "Malware action failed",
    "1116": "Malware detected",
    "1117": "Malware action taken",
    "1118": "Malware action failed",
    "1119": "Malware remediation failed",
    "1120": "Malware remediation succeeded",
    "1121": "Behavior blocked",
    "1122": "Behavior allowed",
    "1150": "Threat quarantined",
    "1151": "Threat restored",
    "5001": "Real-time protection disabled",
    "5004": "Real-time protection enabled",
    "5007": "Configuration changed",
  },
  terminalservices_lsm: {
    "21": "Remote Desktop logon succeeded",
    "22": "Remote Desktop shell start",
    "23": "Remote Desktop logoff",
    "24": "Remote Desktop session disconnected",
    "25": "Remote Desktop session reconnected",
    "39": "Remote Desktop session disconnected by session manager",
    "40": "Remote Desktop session reconnected by session manager",
  },
  terminalservices_rcm: {
    "1149": "User authentication succeeded",
    "1152": "Session login failed",
    "1153": "Session login succeeded",
  },
  winrm: {
    ...(NSA_RECOMMENDED_EVENT_DESCRIPTIONS.winrm ?? {}),
    "6": "WSMan session initialize",
    "16": "WSMan shell created",
    "31": "WSMan command invoked",
    "91": "WSMan plugin started",
    "142": "WSMan user authentication",
    "145": "WSMan user authorization",
    "169": "WSMan operation completed",
  },
  applocker: {
    ...(NSA_RECOMMENDED_EVENT_DESCRIPTIONS.applocker ?? {}),
    "8002": "EXE/DLL allowed",
    "8003": "EXE/DLL blocked",
    "8004": "MSI/Script allowed",
    "8005": "MSI/Script blocked",
    "8006": "Packaged app allowed",
    "8007": "Packaged app blocked",
    "8028": "Config converted to audit mode",
    "8029": "Config converted to enforce mode",
  },
};

export const KNOWN_EVENT_CODE_PROVIDERS = Object.freeze(
  Object.keys(PROVIDER_EVENT_CODE_DESCRIPTIONS).sort()
);

function normalizeProviderKey(provider?: string, channel?: string): string | undefined {
  const p = (provider ?? "").toLowerCase();
  const c = (channel ?? "").toLowerCase();
  if (p.includes("sysmon") || c.includes("sysmon")) return "sysmon";
  if (p.includes("taskscheduler") || c.includes("taskscheduler")) return "taskscheduler";
  if (p.includes("windows defender") || p.includes("defender") || c.includes("windows defender")) return "defender";
  if (p.includes("terminalservices-localsessionmanager") || c.includes("terminalservices-localsessionmanager")) {
    return "terminalservices_lsm";
  }
  if (p.includes("terminalservices-remot") || c.includes("terminalservices-remoteconnectionmanager")) {
    return "terminalservices_rcm";
  }
  if (p.includes("windows remote management") || p.includes("winrm") || c.includes("winrm")) return "winrm";
  if (p.includes("applocker") || c.includes("applocker")) return "applocker";
  if (p.includes("security-auditing") || c.includes("security")) return "security";
  if (p.includes("powershell") || c.includes("powershell")) return "powershell";
  if (c.includes("system") || p.includes("service control manager")) return "system";
  return undefined;
}

export function describeEventCode(code: string, provider?: string, channel?: string): string | undefined {
  const providerKey = normalizeProviderKey(provider, channel);
  if (providerKey) {
    const providerMap = PROVIDER_EVENT_CODE_DESCRIPTIONS[providerKey];
    if (providerMap?.[code]) return providerMap[code];
    const nsaProviderMap = NSA_RECOMMENDED_EVENT_DESCRIPTIONS[providerKey];
    if (nsaProviderMap?.[code]) return nsaProviderMap[code];
  }
  if (SECURITY_AUDIT_EVENT_DESCRIPTIONS[code]) return SECURITY_AUDIT_EVENT_DESCRIPTIONS[code];
  return COMMON_EVENT_CODE_DESCRIPTIONS[code];
}

export function formatEventTypeLabel(eventType: string, provider?: string, channel?: string): string {
  const normalized = eventType.trim();
  const code = normalized.match(/^\d+$/)?.[0];
  if (!code) return normalized;
  const desc = describeEventCode(code, provider, channel);
  return desc ? `${code} - ${desc}` : normalized;
}
